### ISSUE TITLE
Including a external function

### ISSUE THREAD

**Issue by wksauter** [raullaasner/gadfit#1]
Thanks for the code! 

I was able to compile pointing to the path of the library and run the examples successfully.

But I'm having some difficulty in including the special functions of the GSL library in my programs. I tried to include the Li_2 function in the examples but I did not succeed. The output is as follows:
  PATHTOTHECODE/gadfit-1.2.3/tests/example.f90: 29: 11:

      Print *, Li2 (10.0)
            1
Error: There is no specific function for the generic 'li2' at (1)

Any tips to solve this problem?

Thanks!

**Comment by raullaasner** [comment]
Hi wksauter,

In order to use anything from the GSL library, is must be specified during configuring. Run `ccmake` on your build directory, and point `GSL_DIR` to the GSL directory (e.g., /usr). Then build again and try to run your code.
