### ISSUE TITLE
Fitting multi-dimensional complex-valued time-domain NMR-data

### ISSUE THREAD

**Issue by ormo2** [raullaasner/gadfit#2]
1. The complex-valuedness of NMR-data can after all be handled simply in GADfit as is now.
2. How to tell GADfit to restrict the number of differentiations in the case of fitting all multi-
    dimensional NMR-data simultaneously? In other words, how to meddle in the forming
    of GADfit's Jacobian without being an expert in OOP & coarrays?

Dirk van Ormondt. Delft, Netherlands. 02 April 2019.

**Comment by raullaasner** [comment]
You can manipulate the fitting parameters by making them active/passive. Otherwise, I'm not sure exactly what you mean by restricting the number of differentiations.

**Comment by ormo2** [comment]
Dear Raul,

This is a reply to
-------------------------------------------------------------------------
"Subject: 	Re: [raullaasner/gadfit] number of differentiations (#3)
Date: 	Sat, 06 Apr 2019 08:36:00 -0700

**Comment by ormo2** [comment]
[jacobian.pdf](https://github.com/raullaasner/gadfit/files/3070264/jacobian.pdf)
[for_GADfit.pdf](https://github.com/raullaasner/gadfit/files/3070266/for_GADfit.pdf)

Dear Raul,

This is a new attempt to make my point without
wasting too much of your precious time.

My arguments are in `jacobian.pdf'. This file in turn
refers to `for_GADfit.pdf' which I presented two years
ago (under different name) in an MR group that applies
hyperpolarisation.

Sorry for asking your time. Thank you in advance.
Should you have no time, could you please nonetheless
acknowledge receipt of this email to a weird address?

Best regards,

Dirk.
======================================================
