### ISSUE TITLE
number of differentiations

### ISSUE THREAD

**Issue by ormo2** [raullaasner/gadfit#3]
Thank you for your quick help.
I allude to 2dim-data: N1 samples in dim1-space., N2 samples in dim2-space.
This amounts to Na=N1xN2 samples (datapoints): product, huge.
It seems not necessary to compute that many derivatives.
In my opinion,  Nb = N1+N2 derivatives suffice: sum, limited size.
The Jacobian size needs to be  Na x Npar, though, where Npar is the total number of parameters. 
I wish to build this Jacobian from the Nb derivatives with GADfit.
I can do this with my own simple-minded f90 program (no Levenberg-Marquardt, no coarrays, no OOP,
derivatives analytically obtained from computer algebra).
Tomorrow, 5 April, I am absent. Dirk.

**Comment by raullaasner** [comment]
The number of derivatives calculated is (N1+N2) times a number which is on the order of the number of parameters. For example, with one global and one local fitting parameter, the number of derivatives would be roughly 2*(N1+N2). I don't quite see where N1xN2 comes from. Note that even though there are many more elements in the Jacobian, most of them are set to zero. Any linear algebra that is done on the Jacobian is generally fast anyway and so the extra zeros do not pose a significant problem.

Minor note: it's better to follow the same thread when making new posts. Each Github issue should in principle describe a separate technical question and not be spread over several issues.

**Comment by ormo2** [comment]
Dear Raul, 
[for_GADfit.pdf](https://github.com/raullaasner/gadfit/files/3072001/for_GADfit.pdf)
[jacobian.pdf](https://github.com/raullaasner/gadfit/files/3072005/jacobian.pdf)
This is a new attempt to make my point without wasting too much of your precious time. My arguments are in `jacobian.pdf'. This file in turn refers to `for_GADfit.pdf' which I presented two years ago (under different name) in an MR group that applies hyperpolarisation. Sorry for asking your time. Thank you in advance. Should you have no time, could you please nonetheless acknowledge receipt of this email to a weird address? Best regards, Dirk.
